DROP TABLE IF EXISTS `User_info` ;
CREATE TABLE `User_info`   (
`user_id`    VARCHAR(22)   not  NULL   COMMENT   '主键id',
`account`    VARCHAR(10)   DEFAULT  NULL   COMMENT   '账号',
`passWord`    VARCHAR(200)   DEFAULT  NULL   COMMENT   '密码',
`status`    CHAR(1)   DEFAULT  NULL   COMMENT   '账户状态1正常，2冻结',
`name`    VARCHAR(100)   DEFAULT  NULL   COMMENT   '姓名',
`birthDay`    VARCHAR(6)   DEFAULT  NULL   COMMENT   '生日',
`email`    VARCHAR(100)   DEFAULT  NULL   COMMENT   '邮箱地址',
`mobileNum`    VARCHAR(11)   DEFAULT  NULL   COMMENT   '手机号码',
`flag`    cHAR(1)   DEFAULT  NULL   COMMENT   '是否是管理员 0普通用户,1管理员',
`is_First_Login`    CHAR(1)   DEFAULT  NULL   COMMENT   '是否首次登陆：1是，0否',
`pwd_Update_TIMESTAMP`   TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT NULL    COMMENT   '密码修改时间',
`user_create_TIMESTAMP`    TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP DEFAULT NULL   COMMENT   '用户创建时间',
`password_History`    VARCHAR(500)   DEFAULT  NULL   COMMENT   '密码历史',
PRIMARY KEY  (`user_id`)
)  ENGINE=InnoDB DEFAULT CHARSET=utf8  COMMENT='用户信息表';

DROP TABLE
IF EXISTS `AREA_ITEM`;

CREATE TABLE `AREA_ITEM` (
	`CODE` VARCHAR (4) NOT NULL COMMENT '地区名称主键',
	`NAME` VARCHAR (50) NOT NULL COMMENT '地区名称主键',
	`LEVELNAME` VARCHAR (50) DEFAULT NULL COMMENT '级别',
	`CITYNAME` VARCHAR (50) DEFAULT NULL COMMENT '所属市名称',
	`PROVINCE` VARCHAR (50) DEFAULT NULL COMMENT '所属省名称',
	`TYNAME` CHAR (1) DEFAULT NULL COMMENT '行别',
	PRIMARY KEY (`CODE`, `NAME`)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT = '省市基本信息表';

 DROP TABLE
IF EXISTS `BANK_CNAPS`;

CREATE TABLE `BANK_CNAPS` (
	`CNAPS_CODE` VARCHAR (12) NOT NULL COMMENT '银行联行号',
	`CNAPS_NAME` VARCHAR (500) NOT NULL COMMENT '联行号名称',
	`CNAPS_ADDR` VARCHAR (500) DEFAULT NULL COMMENT '行号地址',
	`CREATE_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
	`LAST_UPDATE_TIME` TIMESTAMP NULL DEFAULT NULL COMMENT '更新时间',
	PRIMARY KEY (`CNAPS_CODE`)
) ENGINE = INNODB DEFAULT CHARSET = utf8 COMMENT = '联行号信息表';

